name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'fix') || contains(github.event.pull_request.labels.*.name, 'preview') }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: ⌛ Setup CI
        uses: variableland/gh-actions/actions/setup-pnpm@main

      - name: 🚀 Preview release
        uses: variableland/gh-actions/actions/preview-release@main
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
