name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: 🔑 Mint vland-bot token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.VLAND_BOT_APP_ID }}
          private-key: ${{ secrets.VLAND_BOT_PRIVATE_KEY }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: ⌛ Setup pnpm
        uses: variableland/gh-actions/actions/setup-pnpm@main

      - name: 🧑‍💻 Configure git user
        run: |
          git config user.name "vland-bot[bot]"
          git config user.email "282456776+vland-bot[bot]@users.noreply.github.com"

      - name: 🚀 Create release PR or publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm changeset publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          LEFTHOOK: 0
